service: barbershop
provider:
  name: aws
  runtime: rust
  memorySize: 128
  environment:
    GITHUB_WEBHOOK_SECRET: '${env:GITHUB_WEBHOOK_SECRET}'
    GITHUB_TOKEN: '${env:GITHUB_TOKEN}'
  stackTags:
    'mup:owner': 'platform-services'
    'mup:productName': '${self:service}'

plugins:
  - serverless-rust

package:
  individually: true

functions:
  barbershop:
    handler: barbershop
    events:
      - http:
          path: '/'
          method: POST
